<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <RootNamespace>Noir.TestFixture</RootNamespace>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>none</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>
</Project>
