"""Deterministic, syntactically verified Smali intent and bytecode templates.

Provides safe, verified Smali code generators for common recurring operations
(startup URL redirect intents, Toast notifications, and permission checks)
so routine modifications do not depend exclusively on open-ended LLM bytecode assembly.
"""

from __future__ import annotations

from noir.patches.smali_validator import SmaliBytecodeValidator


class SmaliTemplateError(Exception):
    """Raised when template generation produces invalid Smali bytecode."""

    pass


def _escape_smali_string(s: str) -> str:
    """Escape special characters in strings for Smali string literals."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _validate_register_name(reg: str, param_name: str) -> None:
    """Verify that reg is a valid Dalvik register name (v<N> or p<N>)."""
    import re

    if not re.match(r"^[vp]\d+$", reg.strip()):
        raise ValueError(
            f"Invalid register identifier '{reg}' for {param_name}. "
            "Dalvik bytecode requires 'v<N>' or 'p<N>' naming."
        )


def _validate_start_reg(start_reg: int) -> None:
    """Verify that start_reg is non-negative."""
    if start_reg < 0:
        raise ValueError(f"start_reg must be non-negative, got {start_reg}")


def _validate_request_code(request_code: int) -> None:
    """Verify that request_code is within valid 32-bit integer limits."""
    if not (-2147483648 <= request_code <= 0xFFFFFFFF):
        raise ValueError(f"request_code {request_code} is out of valid 32-bit integer range")


def generate_url_redirect_smali(
    url: str,
    *,
    context_reg: str = "p0",
    start_reg: int = 0,
    new_task: bool = False,
    validate: bool = True,
) -> str:
    """Generate syntactically verified Smali for a startup URL redirect intent.

    Args:
        url: The web URL to open with the Intent (e.g. 'https://example.com').
        context_reg: The Dalvik register holding the Context or Activity (default 'p0').
        start_reg: Starting index for scratch local registers (uses v{start_reg}..v{start_reg+2}).
        new_task: Whether to set FLAG_ACTIVITY_NEW_TASK (0x10000000) on the Intent.
        validate: Whether to run pre-flight validation on the generated bytecode.

    Returns:
        Deterministic Smali instruction block.
    """
    if not url or not url.strip():
        raise ValueError("URL cannot be empty")
    _validate_start_reg(start_reg)
    _validate_register_name(context_reg, "context_reg")

    escaped_url = _escape_smali_string(url)
    v0 = f"v{start_reg}"
    v1 = f"v{start_reg + 1}"
    v2 = f"v{start_reg + 2}"

    lines = [
        f"# NOIR: Startup URL redirect to {url}",
        f'const-string {v0}, "{escaped_url}"',
        f"invoke-static {{{v0}}}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;",
        f"move-result-object {v0}",
        f"new-instance {v1}, Landroid/content/Intent;",
        f'const-string {v2}, "android.intent.action.VIEW"',
        f"invoke-direct {{{v1}, {v2}, {v0}}}, Landroid/content/Intent;-><init>(Ljava/lang/String;Landroid/net/Uri;)V",
    ]

    if new_task:
        lines.extend(
            [
                f"const/high16 {v2}, 0x10000000",
                f"invoke-virtual {{{v1}, {v2}}}, Landroid/content/Intent;->setFlags(I)Landroid/content/Intent;",
                f"move-result-object {v1}",
            ]
        )

    lines.append(
        f"invoke-virtual {{{context_reg}, {v1}}}, Landroid/content/Context;->startActivity(Landroid/content/Intent;)V"
    )

    code = "\n".join(lines) + "\n"

    if validate:
        res = SmaliBytecodeValidator.validate(code)
        if not res.is_valid:
            raise SmaliTemplateError(
                f"Generated URL redirect template failed pre-flight validation: {res.error_summary}"
            )

    return code


def generate_toast_smali(
    message: str,
    *,
    context_reg: str = "p0",
    start_reg: int = 0,
    duration: int = 0,
    validate: bool = True,
) -> str:
    """Generate syntactically verified Smali for a Toast notification.

    Args:
        message: Notification message to display.
        context_reg: Dalvik register holding Context or Activity (default 'p0').
        start_reg: Starting index for scratch local registers (uses v{start_reg}..v{start_reg+1}).
        duration: 0 for Toast.LENGTH_SHORT, 1 for Toast.LENGTH_LONG.
        validate: Whether to run pre-flight validation on the generated bytecode.

    Returns:
        Deterministic Smali instruction block.
    """
    if duration not in (0, 1):
        raise ValueError("Toast duration must be 0 (SHORT) or 1 (LONG)")
    _validate_start_reg(start_reg)
    _validate_register_name(context_reg, "context_reg")

    escaped_msg = _escape_smali_string(message)
    v0 = f"v{start_reg}"
    v1 = f"v{start_reg + 1}"
    dur_const = "0x1" if duration == 1 else "0x0"

    lines = [
        f'# NOIR: Toast notification "{escaped_msg}"',
        f'const-string {v0}, "{escaped_msg}"',
        f"const/4 {v1}, {dur_const}",
        f"invoke-static {{{context_reg}, {v0}, {v1}}}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;",
        f"move-result-object {v0}",
        f"invoke-virtual {{{v0}}}, Landroid/widget/Toast;->show()V",
    ]

    code = "\n".join(lines) + "\n"

    if validate:
        res = SmaliBytecodeValidator.validate(code)
        if not res.is_valid:
            raise SmaliTemplateError(
                f"Generated Toast template failed pre-flight validation: {res.error_summary}"
            )

    return code


def generate_permission_check_smali(
    permission: str,
    *,
    context_reg: str = "p0",
    start_reg: int = 0,
    granted_label: str = ":cond_perm_granted",
    use_compat: bool = False,
    min_api: int = 23,
    validate: bool = True,
) -> str:
    """Generate syntactically verified Smali for a runtime permission check.

    Supports both platform Context.checkSelfPermission (API 23+) and AndroidX
    ContextCompat.checkSelfPermission (backward-compatible across all API levels).

    Args:
        permission: Permission string (e.g. 'android.permission.INTERNET').
        context_reg: Register holding Context/Activity (default 'p0').
        start_reg: Starting index for scratch register.
        granted_label: Label to jump to if permission is GRANTED (PackageManager.PERMISSION_GRANTED == 0).
        use_compat: If True, invoke ContextCompat.checkSelfPermission.
        min_api: Minimum Android API level target. If < 23 and not use_compat, gates check by SDK_INT.
        validate: Whether to run pre-flight validation on the generated bytecode.

    Returns:
        Deterministic Smali instruction block.
    """
    _validate_start_reg(start_reg)
    _validate_register_name(context_reg, "context_reg")
    v0 = f"v{start_reg}"
    lines = [f"# NOIR: Check permission {permission}"]

    if min_api < 23 and not use_compat:
        # On Android < 23, permissions are granted at install time.
        # Check SDK_INT: if < 23, branch directly to granted_label.
        lines.extend(
            [
                f"sget {v0}, Landroid/os/Build$VERSION;->SDK_INT:I",
                f"add-int/lit8 {v0}, {v0}, -0x17",
                f"if-ltz {v0}, {granted_label}",
            ]
        )

    lines.append(f'const-string {v0}, "{permission}"')
    if use_compat:
        lines.append(
            f"invoke-static {{{context_reg}, {v0}}}, Landroidx/core/content/ContextCompat;->checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I"
        )
    else:
        lines.append(
            f"invoke-virtual {{{context_reg}, {v0}}}, Landroid/content/Context;->checkSelfPermission(Ljava/lang/String;)I"
        )

    lines.extend(
        [
            f"move-result {v0}",
            f"if-eqz {v0}, {granted_label}",
        ]
    )

    code = "\n".join(lines) + "\n"

    if validate:
        # Include target label so label check passes
        validation_snippet = code + f"\n{granted_label}\n"
        res = SmaliBytecodeValidator.validate(validation_snippet)
        if not res.is_valid:
            raise SmaliTemplateError(
                f"Generated permission check template failed pre-flight validation: {res.error_summary}"
            )

    return code


def generate_permission_request_smali(
    permissions: list[str],
    *,
    activity_reg: str = "p0",
    start_reg: int = 0,
    request_code: int = 1001,
    use_compat: bool = False,
    validate: bool = True,
) -> str:
    """Generate syntactically verified Smali for an Activity.requestPermissions call.

    Args:
        permissions: List of permission strings to request.
        activity_reg: Register holding Activity (default 'p0').
        start_reg: Starting local register index.
        request_code: Integer request code (supports full 16/32-bit ranges).
        use_compat: If True, invoke ActivityCompat.requestPermissions.
        validate: Whether to run pre-flight validation on generated bytecode.

    Returns:
        Deterministic Smali instruction block.
    """
    if not permissions:
        raise ValueError("At least one permission must be specified")
    _validate_start_reg(start_reg)
    _validate_register_name(activity_reg, "activity_reg")
    _validate_request_code(request_code)

    v0 = f"v{start_reg}"
    v1 = f"v{start_reg + 1}"
    v2 = f"v{start_reg + 2}"
    count = len(permissions)
    count_insn = f"const/4 {v0}, {count:#x}" if count <= 7 else f"const/16 {v0}, {count:#x}"

    lines = [
        f"# NOIR: Request permissions: {', '.join(permissions)}",
        count_insn,
        f"new-array {v0}, {v0}, [Ljava/lang/String;",
    ]

    for idx, perm in enumerate(permissions):
        idx_insn = f"const/4 {v1}, {idx:#x}" if idx <= 7 else f"const/16 {v1}, {idx:#x}"
        lines.extend(
            [
                idx_insn,
                f'const-string {v2}, "{perm}"',
                f"aput-object {v2}, {v0}, {v1}",
            ]
        )

    req_hex = f"{request_code:#x}"
    if -8 <= request_code <= 7:
        req_insn = f"const/4 {v1}, {req_hex}"
    elif -32768 <= request_code <= 32767:
        req_insn = f"const/16 {v1}, {req_hex}"
    else:
        req_insn = f"const {v1}, {req_hex}"

    lines.append(req_insn)
    if use_compat:
        lines.append(
            f"invoke-static {{{activity_reg}, {v0}, {v1}}}, Landroidx/core/app/ActivityCompat;->requestPermissions(Landroid/app/Activity;[Ljava/lang/String;I)V"
        )
    else:
        lines.append(
            f"invoke-virtual {{{activity_reg}, {v0}, {v1}}}, Landroid/app/Activity;->requestPermissions([Ljava/lang/String;I)V"
        )

    code = "\n".join(lines) + "\n"

    if validate:
        res = SmaliBytecodeValidator.validate(code)
        if not res.is_valid:
            raise SmaliTemplateError(
                f"Generated permission request template failed pre-flight validation: {res.error_summary}"
            )

    return code


def generate_notification_permission_smali(
    *,
    activity_reg: str = "p0",
    start_reg: int = 0,
    request_code: int = 1002,
    granted_label: str = ":cond_notify_granted",
    use_compat: bool = False,
    validate: bool = True,
) -> str:
    """Generate syntactically verified Smali for Android 13+ (API 33, TIRAMISU) POST_NOTIFICATIONS permission.

    On Android < 33, notifications are granted automatically without runtime prompt.
    On Android 33+, checks and requests android.permission.POST_NOTIFICATIONS.
    """
    _validate_start_reg(start_reg)
    _validate_register_name(activity_reg, "activity_reg")
    _validate_request_code(request_code)

    v0 = f"v{start_reg}"
    v1 = f"v{start_reg + 1}"
    v2 = f"v{start_reg + 2}"

    # Gate on SDK_INT >= 33 (0x21)
    lines = [
        "# NOIR: Android 13+ (API 33) POST_NOTIFICATIONS check & request",
        f"sget {v0}, Landroid/os/Build$VERSION;->SDK_INT:I",
        f"const/16 {v1}, 0x21",
        f"if-lt {v0}, {v1}, {granted_label}",
        f'const-string {v0}, "android.permission.POST_NOTIFICATIONS"',
    ]

    if use_compat:
        lines.append(
            f"invoke-static {{{activity_reg}, {v0}}}, Landroidx/core/content/ContextCompat;->checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I"
        )
    else:
        lines.append(
            f"invoke-virtual {{{activity_reg}, {v0}}}, Landroid/content/Context;->checkSelfPermission(Ljava/lang/String;)I"
        )

    lines.extend(
        [
            f"move-result {v0}",
            f"if-eqz {v0}, {granted_label}",
            # Request POST_NOTIFICATIONS
            f"const/4 {v0}, 0x1",
            f"new-array {v0}, {v0}, [Ljava/lang/String;",
            f"const/4 {v1}, 0x0",
            f'const-string {v2}, "android.permission.POST_NOTIFICATIONS"',
            f"aput-object {v2}, {v0}, {v1}",
        ]
    )

    req_hex = f"{request_code:#x}"
    if -8 <= request_code <= 7:
        req_insn = f"const/4 {v1}, {req_hex}"
    elif -32768 <= request_code <= 32767:
        req_insn = f"const/16 {v1}, {req_hex}"
    else:
        req_insn = f"const {v1}, {req_hex}"

    lines.append(req_insn)
    if use_compat:
        lines.append(
            f"invoke-static {{{activity_reg}, {v0}, {v1}}}, Landroidx/core/app/ActivityCompat;->requestPermissions(Landroid/app/Activity;[Ljava/lang/String;I)V"
        )
    else:
        lines.append(
            f"invoke-virtual {{{activity_reg}, {v0}, {v1}}}, Landroid/app/Activity;->requestPermissions([Ljava/lang/String;I)V"
        )

    code = "\n".join(lines) + "\n"

    if validate:
        val_code = code + f"\n{granted_label}\n"
        res = SmaliBytecodeValidator.validate(val_code)
        if not res.is_valid:
            raise SmaliTemplateError(
                f"Generated notification permission template failed pre-flight validation: {res.error_summary}"
            )

    return code


def wrap_smali_method(
    instructions: str,
    method_signature: str,
    *,
    access_flags: str = "public",
    locals_count: int = 4,
    class_descriptor: str = "Lcom/noir/GeneratedHelper;",
) -> str:
    """Wrap an instruction block inside a complete Smali .method ... .end method block.

    Args:
        instructions: Smali bytecode instructions.
        method_signature: Method name and descriptor (e.g. 'triggerStartupRedirect(Landroid/content/Context;)V').
        access_flags: Method modifiers (e.g. 'public static' or 'public').
        locals_count: Declared .locals count.
        class_descriptor: Optional class descriptor context.

    Returns:
        Complete syntactically verified Smali method block.
    """
    if locals_count <= 0:
        raise ValueError(f"locals_count must be positive, got {locals_count}")

    import re

    return_type = method_signature.split(")")[-1].strip()
    min_locals = 1
    if return_type in ("J", "D"):
        min_locals = max(min_locals, 2)
    reg_nums = [int(m.group(1)) for m in re.finditer(r"\bv(\d+)\b", instructions)]
    if reg_nums:
        min_locals = max(min_locals, max(reg_nums) + 1)
    actual_locals = max(locals_count, min_locals)

    indented = "\n".join(
        f"    {line}" if line.strip() else "" for line in instructions.strip().splitlines()
    )
    if return_type == "V":
        return_insn = "    return-void"
    elif return_type in ("J", "D"):
        return_insn = "    return-wide v0"
    elif return_type in ("Z", "B", "S", "C", "I", "F"):
        return_insn = "    return v0"
    else:
        return_insn = "    return-object v0"

    code_lines = [
        line.strip()
        for line in instructions.strip().splitlines()
        if line.strip()
        and not line.strip().startswith("#")
        and not line.strip().startswith(".")
        and not line.strip().startswith(":")
    ]
    has_terminal_return = bool(
        code_lines
        and code_lines[-1].startswith(
            ("return-void", "return", "return-object", "return-wide", "throw")
        )
    )
    return_block = "" if has_terminal_return else f"\n{return_insn}\n"

    method_code = (
        f".method {access_flags} {method_signature}\n"
        f"    .locals {actual_locals}\n\n"
        f"{indented}\n"
        f"{return_block}"
        f".end method\n"
    )

    res = SmaliBytecodeValidator.validate(method_code, context_class=class_descriptor)
    if not res.is_valid:
        raise SmaliTemplateError(
            f"Wrapped method failed pre-flight validation: {res.error_summary}"
        )

    return method_code
